variable "environment" {}
variable "region" {}
variable "metrics_namespace" {}
variable "parameter_memcached_location" {}
variable "api_server_host" {}
variable "api_server_port" {}
variable "ecs_instances_desired_count" {}
variable "ecs_instances_memory" {}
variable "ecs_instances_cpu" {}
variable "ecs_cluster_id" {}
variable "ecs_instances_log_configuration" {}
variable "ecs_instances_role_name" {}
variable "ecs_days_to_keep_images" {}
variable "puller_queue_batch_size" {}
variable "puller_response_queue_batch_size" {}
variable "puller_response_queue_max_items_to_process" {}
variable "puller_queue_url" {}
variable "puller_queue_arn" {}
variable "puller_response_queue_url" {}
variable "puller_response_queue_arn" {}
variable "process_name" {}
variable "project_github_location" {}
variable "build_logs_bucket_id" {}
variable "buildspec_location" {}
variable "file_path" {}
variable "file_path_common" {}
variable "build_service_role_arn" {}
variable "build_artifacts_bucket_id" {}
variable "build_artifacts_encryption_key_id" {}
variable "pipeline_service_role_arn" {}
variable "ecs_cluster_name" {}