version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y yarn
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - cd frontend
      - yarn install
  build:
    commands:
      - echo Entered the build phase...
      - cd frontend
      - yarn build --mode=production
  post_build:
    commands:
      - echo Entered the post_build phase...
      - cd frontend
      - yarn deploy --mode=$ENVIRONMENT
