variable "name" {}
variable "environment" {}
variable "region" {}
variable "instances_desired_count" {}
variable "instances_memory" {}
variable "instances_cpu" {}
variable "cluster_id" {}
variable "instances_log_configuration" {}
variable "instances_role_name" {}
variable "instances_extra_policy_arn" {}
variable "container_repository_url" {}