variable "environment" {}
variable "region" {}
variable "metrics_namespace" {}
variable "parameter_memcached_location" {}
variable "mysql_database_host" {}
variable "mysql_database_port" {}
variable "mysql_database_username" {}
variable "mysql_database_password" {}
variable "mysql_database_name" {}
variable "mysql_database_min_batch_size" {}
variable "mysql_database_maxretries" {}
variable "ecs_instances_desired_count" {}
variable "ecs_instances_memory" {}
variable "ecs_instances_cpu" {}
variable "ecs_cluster_id" {}
variable "ecs_instances_log_configuration" {}
variable "ecs_instances_role_name" {}
variable "ecs_days_to_keep_images" {}
variable "input_queue_batch_size" {}
variable "input_queue_max_items_to_process" {}
variable "input_queue_long_polling_seconds" {}