variable "environment" {}
variable "region" {}
variable "metrics_namespace" {}
variable "parameter_memcached_location" {}
variable "api_server_host" {}
variable "api_server_port" {}
variable "ecs_instances_desired_count" {}
variable "ecs_instances_memory" {}
variable "ecs_instances_cpu" {}
variable "ecs_cluster_id" {}
variable "ecs_instances_log_configuration" {}
variable "ecs_instances_role_name" {}
variable "ecs_days_to_keep_images" {}
variable "puller_queue_batch_size" {}
variable "scheduler_seconds_between_user_data_updates" {}
variable "ingester_database_queue_url" {}
variable "ingester_database_queue_arn" {}
variable "max_iterations_before_exit" {}
variable "sleep_ms_between_iterations" {}