variable "environment" {}
variable "cluster_name" {}
variable "region" {}
variable "availability_zone" {}
variable "local_machine_cidr" {}
variable "node_type" {}
variable "cluster_min_size" {}
variable "cluster_max_size" {}
variable "cluster_desired_size" {}