variable "cluster_name" {}
variable "region" {}
variable "availability_zone" {}
variable "local_machine_cidr" {}
variable "instance_type" {}
variable "cluster_desired_size" {}
variable "cluster_min_size" {}
variable "cluster_max_size" {}
variable "local_machine_public_key" {}
variable "instances_desired_count" {}
variable "instances_memory" {}
variable "instances_cpu" {}
variable "instances_log_retention_days" {}