variable "environment" {}
variable "region" {}
variable "parameter_memcached_location" {}
variable "memcached_location" {}
variable "memcached_ttl" {}
variable "ecs_instances_desired_count" {}
variable "ecs_instances_memory" {}
variable "ecs_instances_cpu" {}
variable "ecs_cluster_id" {}
variable "ecs_instances_log_configuration" {}
variable "ecs_instances_role_name" {}
variable "ecs_days_to_keep_images" {}
variable "flickr_api_key" {}
variable "flickr_secret_key" {}
variable "flickr_user_id" {}
variable "flickr_api_retries" {}
variable "flickr_api_favorites_max_per_call" {}
variable "flickr_api_favorites_max_to_get" {}
variable "flickr_api_favorites_max_calls_to_make" {}
variable "output_queue_url" {}
variable "output_queue_arn" {}
variable "output_queue_batch_size" {}
variable "scheduler_queue_url" {}
variable "scheduler_queue_arn" {}
variable "scheduler_queue_batch_size" {}
variable "scheduler_queue_max_items_to_process" {}
variable "scheduler_response_queue_url" {}
variable "scheduler_response_queue_arn" {}
variable "scheduler_response_queue_batch_size" {}